server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    driver-class-name: ${DB_DRIVER_CLASS:org.h2.Driver}
    url: ${DB_JDBC_URL:jdbc:h2:mem:springboot_scaffold}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:password}
    hikari:
      maximum-pool-size: 10
      connection-timeout: 15000
      connection-init-sql: SELECT 1
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:true}
      path: ${H2_CONSOLE_PATH:/h2-console}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: ${DB_JPA_DIALECT:org.hibernate.dialect.H2Dialect}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true

site:
  static-base-url: ${STATIC_BASE_URL:https://freebooklist.s3.ap-southeast-1.amazonaws.com/}
  translator-base-url: ${TRANSLATOR_BASE_URL:https://word.runlala.com}
  translator-api-key: ${TRANSLATOR_API_KEY:c14716c5f5a22e0b5794df09c9e7d62d}
  translator-translate-path: ${TRANSLATOR_TRANSLATE_URI:/translate}
  translator-languages-path: ${TRANSLATOR_LANGUAGES_URI:/languages}
  translator-audio-path: ${TRANSLATOR_AUDIO_URI:/audio}